### ISSUE TITLE
Clustering not in dev does not works until chaning this to same IP address as cluster

### ISSUE THREAD

**Issue by dzmitry-lahoda** [Kritner-Blogs/OrleansGettingStarted#15]
https://github.com/Kritner-Blogs/OrleansGettingStarted/blob/72d03ec452c1f38b0552d2cb1235c4dd21912ef3/src/Kritner.OrleansGettingStarted.SiloHost/Program.cs#L67

I replaced 

```
                .Configure<EndpointOptions>(options => options.AdvertisedIPAddress = IPAddress.Loopback)
```

with 
```
.Configure<EndpointOptions>(options => options.AdvertisedIPAddress = IPAddress.Parse("192.168.88.139")) // my IP in local network
```
and it started to work.

`.Configure<EndpointOptions>` seems should be behind environment switch.

**Comment by Kritner** [comment]
Thanks! guess I missed that, make a few updates to the silo host bootstrapping and made sure i could communicate client -> server with both dev and non dev configurations.
